Repository vuex-orm/vuex-orm, pull requests merged in 2018-08, with the labels that each got.

#210 updated Guide > Plugins section with the current list of components
  docs/guide/digging-deeper/plugins.md
Labels: bug, documentation

#203 Ignore create pivot record
  src/attributes/relations/BelongsToMany.ts
  test/feature/relations/BelongsToMany.spec.js
  test/unit/query/Query_Create_BelongsToMany.spec.js
Labels: bug

#213 Implement sum aggregate
  docs/guide/store/retrieving-data.md
  src/query/Query.ts
  test/unit/query/Query_Aggregates.spec.js
Labels: enhancement

#206 Incremnt nested object with childrent id of null
  src/schema/IdAttribute.ts
  src/schema/ProcessStrategy.ts
  test/feature/attributes/Increment.spec.js
Labels: enhancement
