Repository vuex-orm/vuex-orm, pull requests merged in 2019-05, with the labels that each got.

#353 Tiny typo fix
  docs/guide/store/inserting-and-updating-data.md
Labels: documentation

#363 #303 Fix belongs to many not working when creating data with `increment` id
  src/attributes/relations/BelongsToMany.ts
  src/query/processors/Processor.ts
  test/feature/relations/BelongsToMany_Persist.spec.js
Labels: bug

#371 Add string[] to Query.with name parameter
  src/query/Query.ts
Labels: enhancement

#361 #352 String id for Has Many Through relationship
  test/feature/relations/HasManyThrough.spec.js
Labels: enhancement

#374 #304 Fix `toString` error when the primary key value is `null`
  src/query/processors/IdFixer.ts
  test/feature/basics/Insert.spec.js
Labels: bug

#375 #367 Fix where creating morph to many record with incremented id not working correctly
  src/attributes/relations/MorphToMany.ts
  test/feature/relations/MorphToMany_Persist.spec.js
Labels: bug

#376 #349 Move Vuex and Normalizr to dependencies
  package.json
  yarn.lock
Labels: bug

#377 Add information about models: Docs
  docs/guide/prologue/getting-started.md
Labels: documentation
