Repository vuex-orm/vuex-orm, pull requests merged in 2019-10, with the labels that each got.

#468 getting-started.md
  docs/guide/prologue/getting-started.md
Labels: documentation

#466 #460 STI relations should be instantiated with the appropriate class
  src/attributes/relations/BelongsTo.ts
  src/attributes/relations/HasOne.ts
  src/attributes/relations/MorphOne.ts
  src/attributes/relations/MorphTo.ts
  src/attributes/relations/Relation.ts
  test/feature/inheritance/Model_Inheritance_RelationInstantiation.spec.js
Labels: bug

#473 #472 Fix Nuxt SSR throwing error due to array instanceof
  src/query/loaders/Loader.ts
Labels: bug

#459 Refactor index id for composite primary keys
  dist/vuex-orm.common.js
  dist/vuex-orm.esm.js
  dist/vuex-orm.js
  dist/vuex-orm.min.js
  docs/guide/data/deleting.md
  docs/guide/data/retrieving.md
  src/attributes/relations/BelongsToMany.ts
  src/model/Model.ts
  src/modules/Getters.ts
  src/modules/RootGetters.ts
  src/modules/payloads/Actions.ts
  src/query/Query.ts
  src/schema/IdAttribute.ts
  test/feature/basics/Delete_Composite_Key.spec.ts
  test/feature/models/Find.spec.js
  test/feature/relations/BelongsTo.spec.js
  test/feature/relations/BelongsToMany_Persist.spec.js
  test/unit/model/Model.spec.js
Labels: enhancement
