Repository vuex-orm/vuex-orm, pull requests merged in 2019-12, with the labels that each got.

#510 fix: Has Many By wrong words
  docs/guide/model/relationships.md
Labels: documentation

#528 #514 Add context based model access feature
  build/configs.js
  docs/.vuepress/config.js
  docs/README.md
  docs/api/container/container.md
  docs/api/database/database.md
  docs/guide/README.md
  docs/guide/digging-deeper/server-side-rendering.md
  docs/guide/model/retrieving-models.md
  docs/guide/prologue/getting-started.md
  package.json
  src/attributes/relations/MorphTo.ts
  src/container/Container.ts
  src/database/Database.ts
  src/database/Entity.ts
  src/database/Models.ts
  src/database/Modules.ts
  src/index.ts
  src/model/Model.ts
  src/modules/RootGetters.ts
  src/modules/RootMutations.ts
  src/modules/builder/Builder.ts
  src/modules/contracts/Module.ts
  src/query/Query.ts
  src/query/filters/WhereFilter.ts
  src/query/processors/Normalizer.ts
  src/query/processors/PivotCreator.ts
  src/store/install.ts
  src/support/Utils.ts
  src/types/vuex.ts
  test/feature/inheritance/Model_Inheritance_Relations.spec.js
  test/support/Helpers.js
  test/unit/database/Database.spec.ts
  test/unit/model/Model.spec.js
  test/unit/query/Query.spec.js
  yarn.lock
Labels: enhancement

#532 #526 remove index id from toJson method result
  src/model/Model.ts
  src/model/Serialize.ts
  src/model/Serializer.ts
  src/query/Query.ts
  test/feature/relations/MorphTo.spec.js
  test/feature/relations/Persist_NestedMorph.spec.js
  test/unit/model/Model.spec.js
  test/unit/model/Model_Serialization.spec.ts
Labels: bug
