Repository vuex-orm/vuex-orm, pull requests merged in 2020-02, with the labels that each got.

#551 Fixes orderBy bug
  src/support/Utils.ts
  test/feature/basics/Retrieve_OrderBy.spec.js
  test/unit/support/Utils.spec.ts
Labels: bug

#556 docs: fix dead links
  README.md
  docs/README.md
  docs/guide/README.md
Labels: documentation

#542 Insert/retrieve pivot data into/from many to many relationships
  src/attributes/relations/BelongsToMany.ts
  src/attributes/relations/MorphToMany.ts
  src/attributes/relations/MorphedByMany.ts
  src/model/Model.ts
  test/feature/relations/BelongsToMany_Persist.spec.js
  test/feature/relations/BelongsToMany_Retrieve.spec.js
  test/feature/relations/MorphToMany_Persist.spec.js
  test/feature/relations/MorphToMany_Retrieve.spec.js
  test/feature/relations/MorphedByMany_Persist.spec.js
  test/feature/relations/MorphedByMany_Retrieve.spec.js
Labels: enhancement

#579 feat: add `as` method to customize `pivot` attribute name
  docs/guide/data/inserting-and-updating.md
  docs/guide/model/relationships.md
  src/attributes/relations/BelongsToMany.ts
  src/attributes/relations/MorphToMany.ts
  src/attributes/relations/MorphedByMany.ts
  src/model/Model.ts
  test/feature/relations/BelongsToMany_Persist.spec.js
  test/feature/relations/MorphToMany_Persist.spec.js
  test/feature/relations/MorphedByMany_Persist.spec.js
Labels: enhancement
