Repository vuex-orm/vuex-orm, pull requests merged in 2020-03, with the labels that each got.

#574 #486 exists query resolver
  docs/guide/data/retrieving.md
  src/model/Model.ts
  src/query/Query.ts
  test/feature/basics/Exists.spec.ts
Labels: enhancement

#576 Fix broken link to Normalizing State Shape article and composite primary key example
  docs/guide/data/retrieving.md
  docs/guide/prologue/what-is-vuex-orm.md
Labels: documentation

#583 fix: transpiled classes cannot extend native
  src/database/Database.ts
Labels: bug

#564 Prevent mutation of original data structure in insert/create/insertOrUpdate
  src/polyfills/index.ts
  src/query/Query.ts
  src/support/Utils.ts
  test/feature/models/Create.spec.js
  test/feature/models/Insert.spec.js
  test/feature/models/InsertOrUpdate.spec.js
  test/unit/support/Utils.spec.ts
Labels: enhancement

#573 fix(deps): #553 breaking changes in Normalizr 3.5 (v2)
  dist/vuex-orm.common.js
  dist/vuex-orm.esm.js
  dist/vuex-orm.js
  dist/vuex-orm.min.js
  package.json
  src/query/processors/Normalizer.ts
  src/schema/IdAttribute.ts
  src/schema/Schema.ts
  src/support/Utils.ts
  test/unit/support/Utils.spec.ts
  yarn.lock
Labels: enhancement

#589 fix(query): `findIn` should resolve child relations
  src/query/Query.ts
  test/feature/relations/Retrieve_With.spec.js
Labels: bug

#586 fix: nested relationship orderBy constraints
  src/attributes/relations/BelongsTo.ts
  src/attributes/relations/BelongsToMany.ts
  src/attributes/relations/HasMany.ts
  src/attributes/relations/HasManyBy.ts
  src/attributes/relations/HasManyThrough.ts
  src/attributes/relations/HasOne.ts
  src/attributes/relations/MorphMany.ts
  src/attributes/relations/MorphOne.ts
  src/attributes/relations/MorphTo.ts
  src/attributes/relations/MorphToMany.ts
  src/attributes/relations/MorphedByMany.ts
  src/attributes/relations/Relation.ts
  test/feature/basics/Retrieve.spec.js
  test/feature/relations/BelongsToMany_Retrieve.spec.js
  test/feature/relations/HasManyBy.spec.js
  test/feature/relations/MorphMany_Retrieve.spec.js
  test/feature/relations/MorphToMany_Retrieve.spec.js
  test/feature/relations/MorphedByMany_Retrieve.spec.js
Labels: bug

#590 feat(query): add support for composite primary keys in `where` clause.
  docs/guide/data/retrieving.md
  src/model/Model.ts
  src/query/Query.ts
  src/query/options/PrimaryKey.ts
  src/query/options/index.ts
  test/feature/basics/Retrieve_Where_Composite_Key.spec.js
  test/feature/basics/Update.spec.ts
  test/feature/models/Find.spec.js
  test/feature/models/Update.spec.js
  test/unit/model/Model_Utilities.spec.ts
Labels: enhancement

#596 fix: use `isArray` util function to check the type of the array
  src/attributes/relations/BelongsToMany.ts
  src/attributes/relations/MorphToMany.ts
  src/attributes/relations/MorphedByMany.ts
  src/attributes/relations/Relation.ts
  src/model/Model.ts
  src/model/Serialize.ts
  src/modules/Actions.ts
  src/query/Query.ts
  src/query/filters/WhereFilter.ts
  src/query/loaders/Loader.ts
  src/query/processors/Normalizer.ts
  src/query/rollcallers/Rollcaller.ts
  src/schema/IdAttribute.ts
  src/support/Utils.ts
Labels: bug

#597 refactor(query): remove double deep copy
  src/query/processors/Normalizer.ts
Labels: enhancement

#604 fix: wildcard relations should observe constraints (#603)
  docs/guide/data/retrieving.md
  src/query/Query.ts
  src/query/loaders/Loader.ts
  test/feature/relations/Retrieve_With_NestedConstraints.spec.ts
Labels: bug, documentation, enhancement

#591 feat: add repository class (#585)
  src/database/Database.ts
  src/database/HackedDatabase.ts
  src/index.cjs.ts
  src/index.ts
  src/model/Model.ts
  src/plugins/use.ts
  src/query/Query.ts
  src/repository/Repository.ts
  src/store/install.ts
  src/types/index.ts
  src/types/vuex.ts
  test/feature/repositories/Crud_Create.spec.ts
  test/feature/repositories/Crud_Delete.spec.ts
  test/feature/repositories/Crud_Insert.spec.ts
  test/feature/repositories/Crud_InsertOrUpdate.spec.ts
  test/feature/repositories/Crud_New.spec.ts
  test/feature/repositories/Crud_Retrieve.spec.ts
  test/feature/repositories/Crud_Update.spec.ts
  test/feature/repositories/Repository.spec.ts
  test/unit/database/Database.spec.ts
  test/unit/query/Query.spec.ts
  test/unit/support/Utils.spec.ts
  tslint.json
Labels: enhancement

#592 [WIP] feat(model): enable passing data to persistent methods (#554)
  src/model/Model.ts
  src/modules/Actions.ts
  src/modules/options/Actions.ts
  src/modules/payloads/Actions.ts
  src/modules/support/PayloadBuilder.ts
  test/feature/aggregates/Aggregates.spec.ts
  test/feature/attributes/Boolean.spec.ts
  test/feature/attributes/Number.spec.ts
  test/feature/attributes/String.spec.ts
  test/feature/attributes/Uid.spec.ts
  test/feature/basics/Create.spec.ts
  test/feature/basics/Delete.spec.ts
  test/feature/basics/Delete_Composite_Key.spec.ts
  test/feature/basics/Exists.spec.ts
  test/feature/basics/Insert.spec.ts
  test/feature/basics/PersistOptions.spec.ts
  test/feature/basics/Retrieve.spec.ts
  test/feature/basics/Update.spec.ts
  test/feature/hooks/Global.spec.ts
  test/feature/hooks/Global_Create.spec.ts
  test/feature/hooks/Global_Delete.spec.ts
  test/feature/hooks/Global_Update.spec.ts
  test/feature/hooks/Local_Binding.spec.ts
  test/feature/hooks/Local_Create.spec.ts
  test/feature/hooks/Local_Delete.spec.ts
  test/feature/hooks/Local_Insert.spec.ts
  test/feature/hooks/Local_Update.spec.ts
  test/feature/inheritance/Inheritance.spec.ts
  test/feature/inheritance/Inheritance_CRUD.spec.ts
  test/feature/inheritance/Inheritance_Discriminator.spec.ts
  test/feature/inheritance/Inheritance_Relations.spec.ts
  test/feature/models/All.spec.ts
  test/feature/models/Create.spec.ts
  test/feature/models/Insert.spec.ts
  test/feature/models/InsertOrUpdate.spec.ts
  test/feature/models/Query.spec.ts
  test/feature/models/Update.spec.ts
  test/feature/relations/BelongsToMany_Retrieve.spec.ts
  test/feature/relations/HasMany.spec.ts
  test/feature/relations/HasManyBy.spec.ts
  test/feature/relations/HasManyThrough.spec.ts
  test/feature/relations/HasOne.spec.ts
  test/feature/relations/MorphMany_Persist.spec.ts
  test/feature/relations/MorphMany_Retrieve.spec.ts
  test/feature/relations/MorphOne_Persist.spec.ts
  test/feature/relations/MorphOne_Retrieve.spec.ts
  test/feature/relations/MorphTo.spec.ts
  test/feature/relations/MorphToMany_Persist.spec.ts
  test/feature/relations/MorphToMany_Retrieve.spec.ts
  test/feature/relations/MorphedByMany_Persist.spec.ts
  test/feature/relations/MorphedByMany_Retrieve.spec.ts
  test/feature/relations/Persist_NestedMorph.spec.ts
  test/feature/relations/Retrieve_Constraint.spec.ts
  test/feature/relations/Retrieve_DeepLoad.spec.ts
  test/feature/relations/Retrieve_Has.spec.ts
  test/feature/relations/Retrieve_SelfRelation.spec.ts
  test/feature/relations/Retrieve_StringDefine.spec.ts
  test/feature/relations/Retrieve_With.spec.ts
  test/feature/relations/Retrieve_With_NestedConstraints.spec.ts
Labels: enhancement, in progress
